[project]
name = "vix-for-wig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.27.2",
    "ipykernel>=6.29.5",
    "lxml>=5.3.0",
    "pandas>=2.2.3",
    "pyarrow>=18.0.0",
]
